---
after_success:
  - "mvn org.jacoco:jacoco-maven-plugin:prepare-agent coveralls:report"
install:
  - "mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
jdk:
  - openjdk8
language: java
script:
  - "mvn test jacoco:report"